### ISSUE TITLE
[Feature]: Introduce automatic message into object navigation

### ISSUE THREAD

**Issue by cary-rowen** [nvdaes/controlUsageAssistant#6]
### Problem

Object navigation is often difficult for newcomers to NVDA.

### Suggestion

It would be nice if there were also automatic messages during the press of NVDA +numpad4 / Numpad6, Numpad2, Numpad8.
For example, the current navigator object is a list control,
NVDA will report "You can press NVDA+Numpad2 to get to this list..."

the current navigator object is a button control,
NVDA will report "You can press NVDA+Enter to activate the button, or try left-clicking the button (as not all buttons have a default action)"
The above is just an example and may not be rigorous, VoiceOver has that feature, and I think it's helpful to me.

Thanks

**Comment by nvdaes** [comment]
Hello:

For consistency and simplicity, I think we can use the same messages for focus and object navigation. A list of checkboxes can be used to select if automatic messages will be used for focus or object navigation. I think this maybe very easy to include and I may create a PR in the next hours for this, which maybe posted to addonFiles repo as a development version compatible with NVDA 2022.
Please, let me know if you have any concern ith this approach.

**Comment by nvdaes** [comment]
I think that automatic messages in focus narigation maybe the same than focus messages, since the user may explore objects to know how to interact with focus. Anyway, if some object has a default action, this can be added. 

Enviado desde mi iPhone

**Comment by josephsl** [comment]
Hi, while it will definitely benefit touch users. I am a bit cautious about keyboard usage – not all objects can be interacted with the keyboard since object navigation can move to places keyboard focus cannot. Thanks,

**Comment by cary-rowen** [comment]
Thanks and let's look forward to the new features you'll be bringing to the fore. Then discuss again.

**Comment by nvdaes** [comment]
Hi: I"ll try to see if the focus is focusable or not and, in the second case, no message may be presented. Also, a checkbox instead of a list of checkbox may be enough, just if users want to explore with object narigation and have an idea about how to interact when focus is orer them.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
After testing different possibilities, I think it"s better to indicate, for object navigation, if the object can be activated or if the focus can be moved to it. Then the corresponding focus message maybe consulted, since sometimes is useful jost to press NVDa enter. When an action is available, the add-on can inform. Since maybe multiple gestures and this is configurable, maybe better let the user or trainer to decide what gestures to provide for the messages. I"ll implement this probably this weekend for testing.

Enviado desde mi iPhone

**Comment by cary-rowen** [comment]
Thanks for looking into this, it would be useful to report the availability of NVDA+Enter.
Allow NVDA to report if navigating to previous/next objects is allowed, and whether the current navigator object contains child objects.

**Comment by nvdaes** [comment]
For souper-long messages maybe better to press NVda shift h, and aoutomatic messages can provide just essential info like if the object canbe activaded or focused.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Hi again:

According to my last test, I cannot find an accurrate way to see if an object is really focusable. I've tried to use obj.isFocusable and checkoing if controlTypes.State.FOCUSABLE is an element of obj.states, with unaccurate result. So, for now, unless some solid argument against this decission is provided, I'll add the ability to read/listen if an object can be activated when using object navigation.
This issue is about automatic messages, and other features maybe requested later, considering that this is to know what to do with objects, and I think that if a person has pressed a keystroke to navigate, this person should know what is doing and this add-on is mostly to know what to do in the inminent future. Anyway the scope of this issue maybe for short messages.
In case of objects, I'm not avoiding repeated messages since objects with the same role can have or not the ability to be activated.
I expect to post this in addonFiles later or tomorrow, sincewhat I have to do now is to remove the feature related to focusable objects.

**Comment by nvdaes** [comment]
Fixed in PR #7

**Comment by cary-rowen** [comment]
Hi, Has this been merged, I cloned the latest repo and built the add-on, it doesn't seem to take effect.

**Comment by cary-rowen** [comment]
#7 doesn't seem to fully cover what this Issue discusses, will you implement more related features in subsequent releases?

**Comment by cary-rowen** [comment]
@nvdaes

**Comment by nvdaes** [comment]
Hello:

This is blank. I suppose it's a mistake. Otherwise, please let me know.
I know that tihis feature has introduced a bug where if the object can
be activated is reported in the Emoji panel (and maybe others). I'll
try to fix it.

2022-05-28 12:24 GMT+02:00, Rowen ***@***.***>:

**Comment by cary-rowen** [comment]
Hi, I believe this issue does not address my needs at the moment.
I'd like to be able to tell the user if the current object has child objects and how to get to it during object navigation, which is especially useful for newbies.

**Comment by nvdaes** [comment]
Hello: Consider that objects can also have parent, next and previous, and that different gestures can be added and removed, so it"s not the same situation where messages are provided for Windows controls like edit or checkboxes. So, please provide specific info about the design of the feature you would like to see implemented here, for example, if messages should be automatic or not, considering that automatic messages should be short, order of messages, etc. Newvies should see commands and documentation of NVDA, too and we should consider this too. I"m not rejecting your proposal, just trying to address how to implement this in real life and pondering if how and if we can make it useful.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Hello:
We can discuss other features for automatic messages, considering that they have to be short, or more related features if they can be implemented accurately. I have sent a PR to addonFiles and a link to the add-on on the mailing list.

Enviado desde mi iPhone

**Comment by cary-rowen** [comment]
Sorry, this issue seems to have been overlooked by me.
First I would like to say that for the setting: "Message to use when an object can be activated", can we move it after the name and role of the current object, if you hear the same every time you navigate Between the message objects, I think it will reduce efficiency. On the contrary, if you hear the name and role of the current object every time you navigate between objects, then the user can choose whether to interrupt the follow-up message.

**Comment by nvdaes** [comment]
Hi Rowen, seems that this can be done by using wx.CallLater method.
I'll do when I can. Thanks.

2023-02-11 12:04 GMT+01:00, Rowen ***@***.***>:

**Comment by nvdaes** [comment]
@cary-rowen , I've fixed it in PR #11 using wx.CallAfter function.
Feel free to test the attached add-on compressed in .zip (it needs to be extracted to be installed). Please let me know if it doesn't work for you. If we press quickly object navigation keystrokes, the message configured to objects that can be activated will be skipped.

[controlUsageAssistant-0bf2531e23c283f2ef2b7af10b9433cf36375deb.zip](https://github.com/nvdaes/controlUsageAssistant/files/10713994/controlUsageAssistant-0bf2531e23c283f2ef2b7af10b9433cf36375deb.zip)

**Comment by cary-rowen** [comment]
Hi, @nvdaes 
I tried this out and it worked as expected.

Thanks

**Comment by nvdaes** [comment]
> I tried this out and it worked as expected.

OK, I'll share this version on the add-ons mailing list before releasing a stable version with this change, compatible with NVDA 2023.1.
